name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: .go-version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: cdk/.nvmrc

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: cdk/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('cdk/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install CDK dependencies
        run: |
          cd cdk
          npm ci

      - name: Build TypeScript
        run: |
          cd cdk
          npm run build

      - name: Build Go Lambda
        run: |
          cd lambda
          GOOS=linux GOARCH=amd64 go build -o dist/main handler.go

      - name: Run Go unit tests
        run: |
          cd lambda
          go test -v

      - name: Build Go Lambda (for CDK)
        run: |
          cd lambda
          GOOS=linux GOARCH=amd64 go build -o dist/main handler.go

      - name: Run CDK unit tests
        run: |
          cd cdk
          npm run cdk-test

      - name: Verify Go installation
        run: |
          go version
          go env GOROOT
          go env GOPATH

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        run: |
          cd lambda
          golangci-lint run --out-format=colored-line-number

      - name: Run TypeScript linting
        run: |
          cd cdk
          npm run lint